/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/autocomplete/Autocomplete.vue')['default']
    Button: typeof import('./src/components/button/Button.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/Dropdown.vue')['default']
    Field: typeof import('./src/components/field/Field.vue')['default']
    FieldAddon: typeof import('./src/components/field/FieldAddon.vue')['default']
    Frame: typeof import('./src/components/frame/Frame.vue')['default']
    Input: typeof import('./src/components/input/Input.vue')['default']
    Loader: typeof import('./src/components/loader/Loader.vue')['default']
    Option: typeof import('./src/components/option/Option.vue')['default']
    OptionGroup: typeof import('./src/components/option/OptionGroup.vue')['default']
    Progress: typeof import('./src/components/progress/Progress.vue')['default']
    ScrollArea: typeof import('./src/components/scroll-area/ScrollArea.vue')['default']
    Scrollbar: typeof import('./src/components/scroll-area/Scrollbar.vue')['default']
    Select: typeof import('./src/components/select/Select.vue')['default']
    Slider: typeof import('./src/components/slider/Slider.vue')['default']
    Switch: typeof import('./src/components/switch/Switch.vue')['default']
    Textarea: typeof import('./src/components/textarea/Textarea.vue')['default']
    ThemeToggle: typeof import('./src/components/theme-toggle/ThemeToggle.vue')['default']
    Thumb: typeof import('./src/components/thumb/Thumb.vue')['default']
  }
}
